model:
  class_path: models.LIDCDiffusionTraining.LIDCDiffusionTraining
  init_args:
    image_shape:
    - 128
    - 128
    channels: 1
    conditioning: image
    use_random_unconditional_conditioning: false
    ignore_index: null
    step_unrolled_denoising_start_epoch: 99999999
    sigma_data: 0.1
    timesteps: 10
    aggregate_n_samples: 1
    write_full_val_samples: false
    log_all_val_denoising_steps: true
    compute_loss_per_noise_level: true
    #s_churn: 0.0
    #s_max: 80
    use_second_order_correction: true
    train_p_log_mean: 0.75
    model_channels: 64
    #conditioning_noise_factor: 0.0
    #particle_guidance_factor: 0.0
    #pg_s_min: 0.0
    #pg_kernel_type: L2

ckpt_path: null
do_validate: True
do_train: True
do_test: false
seed_everything: 23
